import {useState} from "react";import emailjs from "@emailjs/browser";import {ArrowRight,Check,ChevronDown} from "lucide-react";import {config} from "../config";
const initial={name:"",phone:"",email:"",type:"",date:"",time:"",guests:"",location:"",services:[],budget:"",message:""};
export default function BookingForm({t}){const [form,setForm]=useState(initial);const [status,setStatus]=useState("");const set=(k,v)=>setForm(f=>({...f,[k]:v}));const toggle=s=>set("services",form.services.includes(s)?form.services.filter(x=>x!==s):[...form.services,s]);
const submit=async e=>{e.preventDefault();setStatus("sending");const p={...form,services:form.services.join(", "),business_email:config.businessEmail};if(!config.emailjs.serviceId||!config.emailjs.publicKey||!config.emailjs.clientTemplateId||!config.emailjs.ownerTemplateId){setStatus("not_configured");return;}try{await emailjs.send(config.emailjs.serviceId,config.emailjs.clientTemplateId,p,{publicKey:config.emailjs.publicKey});await emailjs.send(config.emailjs.serviceId,config.emailjs.ownerTemplateId,{...p,to_email:config.businessEmail},{publicKey:config.emailjs.publicKey});setForm(initial);setStatus("success")}catch(err){console.error(err);setStatus("error")}};
return <form onSubmit={submit} className="border border-ink/10 bg-white p-6 text-ink md:p-10"><div className="grid gap-9 md:grid-cols-2"><fieldset><legend className="form-title">{t.booking.personal}</legend><div className="space-y-5 mt-5"><Input label={t.booking.name} required value={form.name} onChange={v=>set("name",v)}/><Input label={t.booking.phone} required value={form.phone} onChange={v=>set("phone",v)}/><Input label={t.booking.email} required type="email" value={form.email} onChange={v=>set("email",v)}/></div></fieldset><fieldset><legend className="form-title">{t.booking.event}</legend><div className="space-y-5 mt-5"><Select label={t.booking.type} required value={form.type} onChange={v=>set("type",v)} options={t.booking.eventTypes} placeholder={t.booking.select}/><div className="grid grid-cols-2 gap-4"><Input label={t.booking.date} required type="date" value={form.date} onChange={v=>set("date",v)}/><Input label={t.booking.time} type="time" value={form.time} onChange={v=>set("time",v)}/></div><div className="grid grid-cols-2 gap-4"><Input label={t.booking.guests} type="number" min="1" value={form.guests} onChange={v=>set("guests",v)}/><Input label={t.booking.location} required value={form.location} onChange={v=>set("location",v)}/></div></div></fieldset></div>
<div className="mt-10 border-t border-ink/10 pt-8"><div className="form-title">{t.booking.services}</div><div className="mt-4 flex flex-wrap gap-2">{t.booking.serviceTypes.map(s=><button type="button" key={s} onClick={()=>toggle(s)} className={`service-pill ${form.services.includes(s)?"selected":""}`}>{form.services.includes(s)&&<Check size={13}/>} {s}</button>)}</div></div>
<div className="mt-8"><Select label={t.booking.budget} value={form.budget} onChange={v=>set("budget",v)} options={t.booking.budgets} placeholder={t.booking.select}/></div><div className="mt-6"><label className="label">{t.booking.message}</label><textarea rows="5" value={form.message} onChange={e=>set("message",e.target.value)} placeholder={t.booking.placeholder} className="field resize-none"/></div>
{status==="not_configured"&&<div className="mt-5 border border-champagne/50 bg-champagne/10 p-4 text-sm">{t.booking.emailNotConfigured}</div>}{status==="error"&&<div className="mt-5 border border-red-300 bg-red-50 p-4 text-sm text-red-700">{t.booking.emailError}</div>}{status==="success"&&<div className="mt-5 border border-green-300 bg-green-50 p-4 text-sm text-green-700">{t.booking.successTitle} {t.booking.successText}</div>}
<button disabled={status==="sending"} className="btn-dark mt-7 w-full justify-center disabled:opacity-50">{status==="sending"?"Sending...":t.booking.submit}<ArrowRight size={17}/></button></form>}
function Input({label,required,value,onChange,type="text",...p}){return <div><label className="label">{label}{required&&" *"}</label><input required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} className="field" {...p}/></div>}
function Select({label,required,value,onChange,options,placeholder}){return <div><label className="label">{label}{required&&" *"}</label><div className="relative"><select required={required} value={value} onChange={e=>onChange(e.target.value)} className="field appearance-none pr-8"><option value="">{placeholder}</option>{options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={16} className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2"/></div></div>}